#!/usr/bin/env node
// Removes generated output from the example fixture.
//
// Runs on prepack so a tarball ships sources only. Without this, `npm pack` includes whatever
// pages happened to be sitting in examples/ from the last local build — stale HTML stamped with
// the packager's machine time, shipped to every installer.
//
// Deletes by generated marker, never by filename: packages/atlas/index.html is a hand-authored
// fixture that must survive, and it survives because it carries no marker. Same rule the
// generator itself uses to decide what it may overwrite.

import { readFileSync, readdirSync, rmSync, statSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const EXAMPLES = join(ROOT, "examples");
const MARKER = "<!-- generated by company-os";

function walk(dir, out = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else if (entry.name.endsWith(".html")) out.push(full);
  }
  return out;
}

let removed = 0, kept = 0;
try { statSync(EXAMPLES); } catch { process.exit(0); }

for (const file of walk(EXAMPLES)) {
  const head = readFileSync(file, "utf8").slice(0, 400);
  const rel = relative(ROOT, file).replace(/\\/g, "/");
  if (head.includes(MARKER)) {
    rmSync(file);
    console.log(`removed ${rel}`);
    removed++;
  } else {
    kept++;
  }
}
console.log(`clean: ${removed} generated file(s) removed, ${kept} hand-authored file(s) kept.`);
