// Intranet discovery and maintenance.
//
// Company OS owns the inventory, health checks, and maintenance policy. Repositories keep
// ownership of their actual pages and page generators. A registered generator may rebuild an
// accepted page, but this module deliberately has no publication, dispatch, deletion, or approval
// capability.

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { spawnSync } from "node:child_process";
import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { readBundledSkill } from "./skills.mjs";

const DEFAULT_EXCLUDES = [
  ".git", ".cache", ".next", ".runtime", ".venv", "venv", "node_modules",
  "coverage", "dist", "build", "tmp", "temp", "editions",
];
const AGENT_MARKER = "company-os:intranet";
const AGENT_START = "<!-- company-os:intranet:start -->";
const AGENT_END = "<!-- company-os:intranet:end -->";
const FORBIDDEN_GENERATOR = /\b(?:publish|deploy|dispatch|ship|send|schedule|blotato|migrate|purge|delete|remove|reset)\b/i;
const SHELL_CONTROL = /(?:&&|\|\||[;|<>])/;

const toPosix = (value) => String(value || "").split(sep).join("/").replace(/^\.\//, "");
const readJson = (path) => {
  try { return JSON.parse(readFileSync(path, "utf8")); } catch { return null; }
};
const statOrNull = (path) => {
  try { return statSync(path); } catch { return null; }
};
const isInside = (root, path) => {
  const rel = relative(root, path);
  return rel === "" || (!rel.startsWith("..") && !isAbsolute(rel));
};
const pageKey = (page) => `${page.projectId}:${toPosix(page.path).toLowerCase()}`;
const safeId = (value) => String(value || "page")
  .toLowerCase()
  .replace(/[^a-z0-9]+/g, "-")
  .replace(/^-+|-+$/g, "") || "page";

function escRe(value) {
  return value.replace(/[|\\{}()[\]^$+?.]/g, "\\$&");
}

export function globToRegExp(pattern) {
  const normalized = toPosix(pattern);
  let source = "";
  for (let i = 0; i < normalized.length; i++) {
    const char = normalized[i];
    if (char === "*" && normalized[i + 1] === "*") {
      i += 1;
      source += normalized[i + 1] === "/" ? "(?:.*/)?" : ".*";
      if (normalized[i + 1] === "/") i += 1;
    } else if (char === "*") source += "[^/]*";
    else if (char === "?") source += "[^/]";
    else source += escRe(char);
  }
  return new RegExp(`^${source}$`, "i");
}

function intranetSpec(config) {
  if (!config.intranet) throw new Error("intranet is not configured; add an intranet block to company-os.config.mjs");
  return config.intranet;
}

function ignored(relativePath, spec) {
  const normalized = toPosix(relativePath);
  const parts = normalized.split("/").filter(Boolean);
  if (parts.some((part) => part.startsWith("."))) return true;
  const names = new Set([...DEFAULT_EXCLUDES, ...(spec.excludeNames || [])].map((value) => String(value).toLowerCase()));
  if (parts.some((part) => names.has(part.toLowerCase()))) return true;
  return (spec.exclude || []).some((pattern) => globToRegExp(pattern).test(normalized));
}

function htmlFacts(path, generatedMark) {
  let html = "";
  try { html = readFileSync(path, "utf8").slice(0, 512_000); } catch {}
  const title = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]
    ?.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
  const heading = html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1]
    ?.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
  const pageId = html.match(/<meta[^>]+name=["']company-os-page-id["'][^>]+content=["']([^"']+)/i)?.[1]
    || html.match(/<meta[^>]+content=["']([^"']+)["'][^>]+name=["']company-os-page-id["']/i)?.[1];
  const generator = html.match(/<meta[^>]+name=["']company-os-generator["'][^>]+content=["']([^"']+)/i)?.[1]
    || html.match(/<meta[^>]+content=["']([^"']+)["'][^>]+name=["']company-os-generator["']/i)?.[1]
    || html.match(/generated by[^>]*?\s[—-]\s*run\s+([^\n>]+?)(?:\s+-->|$)/i)?.[1]?.trim();
  const generated = Boolean(generatedMark && html.slice(0, 500).includes(generatedMark))
    || /generated by (?:company-os|ops-index\/build\.mjs)/i.test(html.slice(0, 500));
  return { title: title || heading || null, pageId, generator, generated };
}

function walkFilesystemIndexes(projectRoot, spec) {
  const found = [];
  const maxDepth = spec.maxDepth ?? 4;
  function visit(dir, depth) {
    if (depth > maxDepth) return;
    let entries = [];
    try { entries = readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const entry of entries) {
      const path = join(dir, entry.name);
      const rel = toPosix(relative(projectRoot, path));
      if (ignored(rel, spec)) continue;
      if (entry.isDirectory()) visit(path, depth + 1);
      else if (entry.isFile() && entry.name.toLowerCase() === "index.html") found.push(path);
    }
  }
  visit(projectRoot, 0);
  return found;
}

function linkedIndexTargets(file, projectRoot, spec) {
  let html = "";
  try { html = readFileSync(file, "utf8"); } catch { return []; }
  const targets = [];
  for (const match of html.matchAll(/\bhref\s*=\s*["']([^"']+)["']/gi)) {
    const href = match[1].trim();
    if (!href || /^(?:[a-z]+:|#|\/\/|\/)/i.test(href)) continue;
    let clean = href.split("#")[0].split("?")[0];
    try { clean = decodeURIComponent(clean); } catch {}
    let target = resolve(dirname(file), clean);
    const stat = statOrNull(target);
    if (stat?.isDirectory()) target = join(target, "index.html");
    if (target.split(/[\\/]/).pop()?.toLowerCase() !== "index.html") continue;
    if (!isInside(projectRoot, target)) continue;
    const rel = toPosix(relative(projectRoot, target));
    if (!ignored(rel, spec) && existsSync(target)) targets.push(target);
  }
  return targets;
}

// Linked discovery follows the repository's own navigation instead of treating every web build
// artifact as an intranet page. Filesystem mode remains available for repositories that explicitly
// want a broad candidate inventory.
function walkLinkedIndexes(projectRoot, spec) {
  const rootIndex = join(projectRoot, "index.html");
  if (!existsSync(rootIndex)) return [];
  const found = [];
  const seen = new Set();
  const queue = [{ file: rootIndex, depth: 0 }];
  const maxDepth = spec.maxDepth ?? 2;
  while (queue.length) {
    const current = queue.shift();
    const key = resolve(current.file).toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    found.push(current.file);
    if (current.depth >= maxDepth) continue;
    for (const target of linkedIndexTargets(current.file, projectRoot, spec)) {
      queue.push({ file: target, depth: current.depth + 1 });
    }
  }
  return found;
}

function walkIndexes(projectRoot, spec) {
  return spec.discovery === "filesystem"
    ? walkFilesystemIndexes(projectRoot, spec)
    : walkLinkedIndexes(projectRoot, spec);
}

export function loadIntranetRegistry(config) {
  const spec = intranetSpec(config);
  return readJson(spec.registry) || {
    schemaVersion: `${config.schemaPrefix}.intranet-registry/v1`,
    pages: [],
  };
}

export function discoverIntranet(config, manifest, { now = new Date() } = {}) {
  const spec = intranetSpec(config);
  const existing = loadIntranetRegistry(config);
  const previous = new Map((existing.pages || []).map((page) => [pageKey(page), page]));
  const pages = [];

  for (const engine of manifest.engines || []) {
    const projectRoot = resolve(config.root, engine.dir);
    if (!existsSync(projectRoot)) continue;
    const projectSettings = spec.projects?.[engine.id] || {};
    const projectSpec = {
      ...spec,
      ...projectSettings,
      excludeNames: [...(spec.excludeNames || []), ...(projectSettings.excludeNames || [])],
      exclude: [...(spec.exclude || []), ...(projectSettings.exclude || [])],
    };
    for (const file of walkIndexes(projectRoot, projectSpec)) {
      const rootPath = toPosix(relative(config.root, file));
      const projectPath = toPosix(relative(projectRoot, file));
      const facts = htmlFacts(file, config.generatedMark);
      const key = `${engine.id}:${rootPath.toLowerCase()}`;
      const old = previous.get(key) || {};
      previous.delete(key);
      const inferredId = projectPath === "index.html"
        ? `${engine.id}-home`
        : `${engine.id}-${safeId(projectPath.replace(/\/index\.html$/i, ""))}`;
      pages.push({
        ...old,
        id: old.id || facts.pageId || inferredId,
        projectId: engine.id,
        projectName: engine.name,
        path: rootPath,
        projectPath,
        title: old.title || facts.title || engine.name,
        registration: old.registration || "candidate",
        ownership: old.ownership || (facts.generated ? "company-os" : "repository"),
        generator: old.generator || facts.generator || null,
        sources: Array.isArray(old.sources) ? old.sources : [],
        maintainOn: Array.isArray(old.maintainOn) ? old.maintainOn : ["source-change", "scheduled-sweep"],
        authority: {
          regenerate: false,
          publish: false,
          delete: false,
          ...(old.authority || {}),
          publish: false,
          delete: false,
        },
        discovered: true,
      });
    }
  }

  for (const page of previous.values()) pages.push({ ...page, discovered: false });
  pages.sort((a, b) => a.projectId.localeCompare(b.projectId) || a.path.localeCompare(b.path));
  return {
    ...existing,
    schemaVersion: `${config.schemaPrefix}.intranet-registry/v1`,
    scannedAt: now.toISOString(),
    pages,
  };
}

export function writeIntranetRegistry(config, registry) {
  const spec = intranetSpec(config);
  mkdirSync(dirname(spec.registry), { recursive: true });
  writeFileSync(spec.registry, `${JSON.stringify(registry, null, 2)}\n`, "utf8");
  return spec.registry;
}

function localLinks(config, page) {
  const file = resolve(config.root, page.path);
  if (!existsSync(file)) return { checked: 0, broken: [] };
  let html = "";
  try { html = readFileSync(file, "utf8"); } catch { return { checked: 0, broken: [] }; }
  const broken = [];
  let checked = 0;
  for (const match of html.matchAll(/\bhref\s*=\s*["']([^"']+)["']/gi)) {
    const href = match[1].trim();
    // Template literals embedded in client-side render functions are not links in the emitted
    // page yet; validating them as literal filenames creates false failures.
    if (!href || href.includes("${") || /^(?:[a-z]+:|#|\/\/)/i.test(href)) continue;
    const clean = href.split("#")[0].split("?")[0];
    if (!clean) continue;
    checked += 1;
    let decoded = clean;
    try { decoded = decodeURIComponent(clean); } catch {}
    const target = decoded.startsWith("/")
      ? resolve(config.root, decoded.replace(/^\/+/, ""))
      : resolve(dirname(file), decoded);
    if (!isInside(config.root, target)) {
      broken.push({ href, reason: "outside company root" });
      continue;
    }
    if (!statOrNull(target)) broken.push({ href, reason: "target missing" });
  }
  return { checked, broken: broken.slice(0, 25) };
}

function sourceFiles(projectRoot, patterns) {
  const found = new Set();
  function visit(dir, regex) {
    let entries = [];
    try { entries = readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const entry of entries) {
      const path = join(dir, entry.name);
      const rel = toPosix(relative(projectRoot, path));
      const parts = rel.split("/");
      if (parts.some((part) => [".git", "node_modules", ".venv", "venv"].includes(part))) continue;
      if (entry.isDirectory()) visit(path, regex);
      else if (entry.isFile() && regex.test(rel)) found.add(path);
    }
  }
  for (const pattern of patterns) {
    const normalized = toPosix(pattern);
    const wildcard = normalized.search(/[*?]/);
    if (wildcard === -1) {
      const exact = resolve(projectRoot, normalized);
      if (statOrNull(exact)?.isFile()) found.add(exact);
      continue;
    }
    const prefix = normalized.slice(0, wildcard);
    const slash = prefix.lastIndexOf("/");
    const base = resolve(projectRoot, slash === -1 ? "." : prefix.slice(0, slash));
    if (!isInside(projectRoot, base)) continue;
    visit(base, globToRegExp(normalized));
  }
  return [...found];
}

function changedSource(page, engine, changedPaths, config) {
  if (!changedPaths.length || !(page.sources || []).length) return false;
  const regexes = page.sources.map(globToRegExp);
  return changedPaths.some((changed) => {
    const absolute = isAbsolute(changed) ? resolve(changed) : resolve(config.root, changed);
    const projectRoot = resolve(config.root, engine.dir);
    if (!isInside(projectRoot, absolute)) return false;
    const rel = toPosix(relative(projectRoot, absolute));
    return regexes.some((regex) => regex.test(rel));
  });
}

function agentState(config, engine, page) {
  const projectRoot = resolve(config.root, engine.dir);
  const ruleFiles = page.agentRules?.files || ["AGENTS.md"];
  const marker = page.agentRules?.marker || AGENT_MARKER;
  const skillFiles = page.agentRules?.skillFiles
    || [".claude/skills/company-os-intranet-maintainer/SKILL.md"];
  const rules = ruleFiles.some((file) => {
    try { return readFileSync(join(projectRoot, file), "utf8").includes(marker); } catch { return false; }
  });
  const skill = skillFiles.some((file) => existsSync(join(projectRoot, file)));
  return {
    rules,
    skill,
    ruleFiles: ruleFiles.map((file) => toPosix(join(engine.dir, file))),
    skillFiles: skillFiles.map((file) => toPosix(join(engine.dir, file))),
  };
}

function generatorAllowed(command) {
  if (!command) return { allowed: false, reason: "no generator declared" };
  if (SHELL_CONTROL.test(command)) return { allowed: false, reason: "generator contains shell control operators" };
  if (FORBIDDEN_GENERATOR.test(command)) return { allowed: false, reason: "generator crosses the publish/delete authority boundary" };
  return { allowed: true, reason: null };
}

function evaluatePage(config, spec, page, engine) {
  const file = resolve(config.root, page.path);
  const pageStat = statOrNull(file);
  const projectRoot = resolve(config.root, engine.dir);
  const sources = sourceFiles(projectRoot, page.sources || []);
  const newestSource = sources.reduce((latest, source) => Math.max(latest, statOrNull(source)?.mtimeMs || 0), 0);
  const stale = Boolean(pageStat && newestSource > pageStat.mtimeMs);
  const links = localLinks(config, page);
  const agent = agentState(config, engine, page);
  let status = "healthy";
  if (!pageStat) status = "missing";
  else if (links.broken.length) status = "broken";
  else if (stale) status = "stale";
  else if (page.registration !== "accepted") status = "needs-review";
  else if (page.ownership === "repository"
    && page.agentMaintenance !== false
    && spec.requireAgentRule !== false
    && (!agent.rules || (spec.requireAgentSkill !== false && !agent.skill))) status = "needs-review";
  return {
    ...page,
    exists: Boolean(pageStat),
    updatedAt: pageStat?.mtime?.toISOString() || null,
    sourceFiles: sources.length,
    newestSourceAt: newestSource ? new Date(newestSource).toISOString() : null,
    stale,
    links,
    agent,
    status,
  };
}

export async function maintainIntranet(config, manifest, {
  mode = "sweep",
  changedPaths = [],
  execute = false,
  writeState = true,
  now = new Date(),
  log = () => {},
} = {}) {
  const spec = intranetSpec(config);
  const registry = discoverIntranet(config, manifest, { now });
  const engines = new Map((manifest.engines || []).map((engine) => [engine.id, engine]));
  const actions = [];
  const pages = [];

  for (const registered of registry.pages) {
    const engine = engines.get(registered.projectId);
    if (!engine) {
      pages.push({ ...registered, status: "unowned", exists: false, links: { checked: 0, broken: [] } });
      continue;
    }
    let page = evaluatePage(config, spec, registered, engine);
    const changed = changedSource(page, engine, changedPaths, config);
    const shouldRun = execute
      && page.registration === "accepted"
      && page.authority?.regenerate === true
      && (page.stale || !page.exists || changed);
    if (shouldRun) {
      const safety = generatorAllowed(page.generator);
      if (!safety.allowed) {
        actions.push({ pageId: page.id, action: "blocked", reason: safety.reason });
        page = { ...page, status: "blocked", maintenanceError: safety.reason };
      } else {
        const projectRoot = resolve(config.root, engine.dir);
        log(`maintain ${page.id}: ${page.generator}`);
        const result = spawnSync(page.generator, {
          cwd: projectRoot,
          encoding: "utf8",
          shell: true,
          timeout: spec.generatorTimeoutMs || 120_000,
        });
        if (result.status === 0) {
          actions.push({ pageId: page.id, action: "regenerated", command: page.generator });
          page = evaluatePage(config, spec, registered, engine);
        } else {
          const detail = String(result.stderr || result.stdout || `exit ${result.status}`).trim().slice(0, 800);
          actions.push({ pageId: page.id, action: "failed", command: page.generator, detail });
          page = { ...page, status: "blocked", maintenanceError: detail };
        }
      }
    }
    pages.push({ ...page, changedSource: changed });
  }

  const summary = {};
  for (const page of pages) summary[page.status] = (summary[page.status] || 0) + 1;
  const state = {
    schemaVersion: `${config.schemaPrefix}.intranet-state/v1`,
    updatedAt: now.toISOString(),
    mode,
    pages,
    actions,
    summary,
  };
  if (writeState && spec.state) {
    mkdirSync(dirname(spec.state), { recursive: true });
    writeFileSync(spec.state, `${JSON.stringify(state, null, 2)}\n`, "utf8");
  }
  return state;
}

export function loadIntranetState(config) {
  const spec = intranetSpec(config);
  return spec.state ? readJson(spec.state) : null;
}

// The skill text lives in skills/company-os-intranet-maintainer/SKILL.md and is read from there.
// It was previously duplicated here as a template literal, and the two copies had already drifted
// apart — see readBundledSkill's note. Kept as a named export so callers can read the text without
// installing it.
export const INTRANET_SKILL = readBundledSkill("intranet-maintainer");

function agentBlock(command) {
  return `${AGENT_START}
## Intranet maintenance

When an interaction changes files covered by a registered intranet page, run its declared generator
and validate the resulting local links before finishing. Use the Company OS maintenance command:

\`${command}\`

Do not hand-edit generated HTML. Refreshing an intranet page does not approve, schedule, dispatch,
publish, delete, or relocate content. Follow the \`company-os-intranet-maintainer\` skill.
${AGENT_END}`;
}

export function installIntranetAgentRules(config, manifest, { projectIds = [] } = {}) {
  const spec = intranetSpec(config);
  const selected = new Set(projectIds);
  const results = [];
  for (const engine of manifest.engines || []) {
    if (selected.size && !selected.has(engine.id)) continue;
    const root = resolve(config.root, engine.dir);
    const agentsPath = join(root, "AGENTS.md");
    const skillPath = join(root, ".claude", "skills", "company-os-intranet-maintainer", "SKILL.md");
    const command = spec.agentCommand || `${config.rebuildCommand} --changed <path>`;
    let agents = "";
    try { agents = readFileSync(agentsPath, "utf8"); } catch {}
    let ruleAction = "kept";
    if (!agents.includes(AGENT_MARKER)) {
      const prefix = agents.trimEnd();
      writeFileSync(agentsPath, `${prefix}${prefix ? "\n\n" : ""}${agentBlock(command)}\n`, "utf8");
      ruleAction = agents ? "appended" : "created";
    }
    let skillAction = "kept";
    if (!existsSync(skillPath)) {
      mkdirSync(dirname(skillPath), { recursive: true });
      writeFileSync(skillPath, INTRANET_SKILL, "utf8");
      skillAction = "created";
    }
    results.push({ projectId: engine.id, ruleAction, skillAction, agentsPath, skillPath });
  }
  return results;
}
